### ISSUE TITLE
Doesn't installing for python 2.7.3

### ISSUE THREAD

**Issue by hustonCun** [alaouimehdi1995/django-rest#30]
![image](https://user-images.githubusercontent.com/18235953/109387675-e3e97700-7913-11eb-9adb-d827baf07413.png)
![image](https://user-images.githubusercontent.com/18235953/109387689-f5cb1a00-7913-11eb-83b1-7109a0f17ae5.png)

**Comment by alaouimehdi1995** [comment]
Hi @hustonCun ! First of all, thanks for opening this issue (and therefore contributing to make the project better). Also, I wanted to apologize for the response delay. I was absent a little bit from Github. I wanted to tell you that the bug has been found and fixed. By installing the last version of `django-rest` (v0.8.7), you will be able to install it without problems on python 2.X environment.

Best regards !
